### PR TITLE
Loo predictive checks

### LINKED ISSUE #72: LOO predictive checks
#### Summary:
Add LOO predictive chesks
- [x] LOO probability integral transformation (PIT) predictive check
- [x] plot of LOO predictive intervals vs. observations

#### Description:
Calibration of the marginal predictions can be checked with probability integral transformation (PIT) checks. LOO improves the check by avoiding the double use of data. See Marginal predictive checks in BDA3 p. 152-153. In addition visual predictive checking can be made by plotting LOO predictive intervals and the observations.

Example code for LOO-PIT (I assume visual predictive checking is close to current ppc plot)

```
data(radon)
y<-radon$log_radon
# Fit the first model
modelA <- stan_lmer(
    log_radon ~ floor + log_uranium + floor:log_uranium + (1 + floor | county),
    data = radon,
    cores = 4,
    iter = 2000,
    chains = 4)

# probability integral transformation (PIT)
# this would be more accurate using conditional cdf's N(y_i|mu^{(s)},sigma^{(s)}
log_likA<-log_lik(modelA, parameter_name = "log_lik")
psisA<-psislw(-log_likA)
predsA<-posterior_predict(modelA)
pitA<-array(0,ncol(predsA))
library(matrixStats)
for (i in 1:ncol(predsA)) {
    pitA[i]<- exp(logSumExp(psisA$lw_smooth[(predsA[,i]<=y[i]),i]))
}

# LOO-PITs should have uniform distribution
par(mfrow=c(1,2))
qqplot(pitA,runif(10000))

```

### PR DESCRIPTION
**Pull request by jgabry**
Introduces `ppc_loo_pit`, `ppc_loo_intervals`, `ppc_loo_ribbon` functions. 

closes #72 

-----

#### Examples

We'll use __rstanarm__ and __loo__ to get stuff to work with in order to demonstrate the `ppc_loo_*` functions (__rstanarm__ user's won't actually need to do all of this because `pp_check` will do it internally.)

```r
library(rstanarm)
library(loo)

fit <- stan_lmer(log_radon ~ floor + log_uranium + floor:log_uranium
                    + (1 + floor | county), data = radon)
y <- radon$log_radon
yrep <- posterior_predict(fit)
lw <- psislw(-log_lik(fit))$lw_smooth
```

LOO PIT check
```r
color_scheme_set("purple")
ppc_loo_pit(y, yrep, lw)
```
loo_pit1

```r
ppc_loo_pit(y, yrep, lw, compare = "normal")
```
loo_pit2

LOO predictive intervals vs observations
```r
ppc_loo_intervals(y[1:50], yrep[, 1:50], lw[, 1:50], prob = 0.5, size = .5)
```
loo_intervals

### CODE REVIEW

**Comment by jgabry** [comment]
@avehtari If these plots look good to you then I think this is ready to go!

**Comment by avehtari** [comment]
Looks good! (Although I still get surprised by 50% intervals...) Btw, do you have also an example where ppc_loo_pit(y, yrep, lw, compare = "normal") would produce a straight line?

**Comment by jgabry** [comment]
The default is 90% intervals. I just put 50% here to give an example of how
to change it.

As for compare="normal", I'm not sure  off the top of my head but I know I
saw a few decent examples when I was working on it and testing various
models. I'll see what I can find.

On Mon, Mar 27, 2017 at 5:39 PM Aki Vehtari <notifications@github.com>
wrote:

Looks good! (Although I still get surprised by 50% intervals...) Btw, do
you have also an example where ppc_loo_pit(y, yrep, lw, compare = "normal")
would produce a straight line?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/stan-dev/bayesplot/pull/82#issuecomment-289594441>, or mute
the thread

**Comment by jgabry** [comment]
Great, thanks Aki

**Comment by avehtari** [comment]
Sorry I realized this bit late, but it would be nice to have option to plot the intervals sorted based on median.

**Comment by jgabry** [comment]
I can add that. Do you think the sorted version should be the default?

**Comment by jgabry** [comment]
@avehtari I just added an argument for this to `ppc_loo_intervals`. You can now do

```r
ppc_loo_intervals(..., order = "index")  # default
ppc_loo_intervals(..., order = "median")
```

**Pull request merged**
