### PR TITLE
Restructuring and clarifying the diagnostic vignette

### PR DESCRIPTION
**Pull request by martinmodrak**
As discussed in #144, I made some changes to the diagnostic vignette to (IMHO) be more close to a modeller's workflow.

### CODE REVIEW

**Comment by jgabry** [comment]
@martinmodrak Actually I was thinking about your comment in #144 about starting with the NUTS diagnostics before stuff like Rhat, and you're right that it would be closer to actual workflow. Do you want to take a stab at that before I merge this?

**Comment by martinmodrak** [comment]
I'll have a go at it. I also notice some minor typos etc. However, I need to keep the seed (or add seed argument) as the traceplot zoom example may break with another seed. Note that `set.seed` has effect on Stan, because the `seed` argument of `sampling` defaults to `sample.int(.Machine$integer.max, 1)`

**Comment by jgabry** [comment]
I forgot that was the default we have for the seed argument. It won’t
reproduce across different systems but should reproduce on your own system.
Anyway, feel free to add back in the set.seed call.

**Comment by martinmodrak** [comment]
I didn' realize `set.seed` won't reproduce across systems. So I moved to setting the `seed` argument of `sampling`. Also there was a bug as the `n_eff` extractor forces `n_eff / n_samples` to be < 1, which is no longer true in recent Stan (see https://github.com/stan-dev/stan/issues/2450), so I fixed that as well (I didn't bothe rcreating a separate branch for this fix, hop its OK). That's probably all from me, unless you have some other comments.

**Comment by jgabry** [comment]
(Accidentally closed this, so reopening)

**Comment by martinmodrak** [comment]
I initially added the seeds primarily for the traceplot zoom example - I want to focus on the area where divergences arise. While working on the vignette, I also noticed multiple uncommon situations where the vignette ceases to be illustrative:

* Very few or no divergences for the centered parametrization
* Small `Rhat` for all parameters with the short chain example
* One or two divergences in the non-centered parametrization

While I understand that all the conditions for reproducibility have to hold to *guarantee* reproducibility, I would guess that in practice, setting seed would be enough for the results to reproduce well unless the Stan core changes (the RNG in Stan is hardcoded so should not be system dependent). Also we could probably setup some checks and make the vignette fail in those weird cases with something like "Low Rhat in this example, change seed" to make sure the vignette stays relevant.

**Comment by jgabry** [comment]
That all makes sense. I do think R’s set.seed works the same across systems, so you could go back to using that if you want. That won’t guarantee the same Stan results but your proposed solution of forcing it to fail in some cases is a good one I think.

**Comment by martinmodrak** [comment]
Checks added.

**Comment by jgabry** [comment]
@martinmodrak I think this is ready for me to merge, but I had to change one of the seeds to avoid getting a divergence in the NCP model. Does the new seed I changed it to work ok on your end?

**Comment by avehtari** [comment]
Couple comments

1)
> Also there was a bug as the n_eff extractor forces n_eff / n_samples to be < 1, which is no longer true in recent Stan (see stan-dev/stan#2450), so I fixed that as well

To test how the plots look like with high n_eff / n_samples you can use this model
```
parameters {
  vector[16] x;
}
model {
  x ~ normal(0, 1);
}
```
which has n_eff / n_samples > 2.

2)
8 schools NCP has often divergences with the default adapt_delta. Instead of trying to choose random seed (that would work on all platforms), I would use adapt_delta=0.95 (or higher) already for the first fit to make the vignette to produce more consistent results.

**Comment by avehtari** [comment]
> Those functions require more information than simply the posterior samples,
> ...
> That is, even though the samples for tau returned from Stan
> ...
> to obtain samples from the funnel distribution
> ...
> and no samples in the tail of the distribution
> ...
> the ratio of the average variance of samples within each chain to the variance of the pooled samples across chains
> ...
> (it means samples are not independent)

- samples -> draws (following the recommendation by Andrew: a sample is a collection of draws)

> when tau, the hierarchical standard deviation, goes to zero

- goes near zero?

> Then theta is computed deterministically from the parameters eta,mu and tau

- add space after "eta,"

> This is the motivation for the Gelman and Rubin (1992) potential scale reduction statistic

- split-$\hat{R}$ which is used has changed substantially since this paper, and it would be better to use term split-$\hat{R}$ and cite Gelman et al (2013) and Stan manual.

> The effective sample size

- cite Gelman et al (2013) and Stan manual for the algorithm used to compute n_eff

> Autocorrelation is bad (it means samples are not independent) and you want it to drop quickly to zero with increasing lag.

- samples -> draws
- negative autocorrelation is not bad, and non-independent draws can be more efficient than independent

**Comment by avehtari** [comment]
Clarification: I don't suggest adding the normal model to the vignette. Just check that plots look good with n_eff / n > 2. I guess I should have had that comment somewhere else, but since that n_eff fix was also in this pull request...

**Comment by jgabry** [comment]
Thanks Aki. In particular, I think this is a good idea: 

> 8 schools NCP has often divergences with the default adapt_delta. Instead of trying to choose random seed (that would work on all platforms), I would use adapt_delta=0.95 (or higher) already for the first fit to make the vignette to produce more consistent results.

@martinmodrak Are you ok with that?

**Comment by martinmodrak** [comment]
Thanks Aki for the suggestions. I changed all references to "samples" as individual rows in the Stan output to "draws". And I added `adapt_delta` for the initial fits.

The scary thing is that I obviously was wrong about reproducibility and Stan produces mutually different results on my PC, Jonah's PC and the CI server :-O

I am a bit uncertain, how to discuss negative autocorrelation - in particular, I don't really understand how `n_eff > n` actually works - how can you get better than independent samples from the posterior? Does it mean that for any/some function(s) `f`, `f(draws)` approaches the `f(true_target)` faster than `f(independent_draws_from_true_target)`? Or is `n_eff` actually a measure of something a bit different than the number of independent samples from the posterior? Also too much negative autocorrelation would also be bad, wouldn't it? How to check that there is "healthy" negative autocorrelation? Do you have a formulation in mind that would be clear? Otherwise I'll need some time to understand the literature on that to not give misleading interpretations.

I modified the note about Rhat (and it no longer is a citation from the manual). However, please, do not refer to sources by author and year only - for people outside the niche (like me), it is often hard to determine which paper/book is meant. I guess you meant BDA 3?

I have adjusted the `mcmc_neff` plot to not truncate `n_eff > 1`. Sorry for mangling the `n_eff` fix with this pull request.

**Comment by avehtari** [comment]
> I am a bit uncertain, how to discuss negative autocorrelation - in particular, I don't really understand how n_eff > n actually works - how can you get better than independent samples from the posterior? 

See a simple example in 
http://andrewgelman.com/2018/01/18/measuring-speed-stan-incorrectly-faster-thought-cases-due-antithetical-sampling/

>  Does it mean that for any/some function(s) f, f(draws) approaches the f(true_target) faster than f(independent_draws_from_true_target)

Yes. There are examples here http://discourse.mc-stan.org/t/n-eff-bda3-vs-stan/2608/19

> Also too much negative autocorrelation would also be bad, wouldn't it?

No. But you can't get correlation -1 in lag 1, except for binary case

> Do you have a formulation in mind that would be clear? 

Unfortunately I know too much and formulations are likely to be clear for me, but not necessarily for others.

> Otherwise I'll need some time to understand the literature on that to not give misleading interpretations.

I think it's good idea if check those couple links, and then continue discussion to arrive a formulation which would be clear also for wider audience. 

> However, please, do not refer to sources by author and year only - for people outside the niche (like me), it is often hard to determine which paper/book is meant. I guess you meant BDA 3?

Sorry, I guessed it would be clear as it was already listed in the references :)

Also, great that you are interested in improving the documentation!

**Comment by martinmodrak** [comment]
OK, let me give it a try, I would add a footnote to the explanation of `n_eff`. The statement about other functions computed from draws is a guess - does it make sense?:

`n_eff > N` means that the mean value of the parameter computed from Stan draws approaches the true mean faster then independent samples from the true posterior (the estimate from Stan has smaller variance). This is possible when the draws are anticorrelated - draws above the mean tend to be well matched with draws below the mean. Other functions computed from draws (quantiles, posterior intervals, tail probabilities) may not necessarily approach the true posterior faster. Google "antithetic sampling" or visit http://discourse.mc-stan.org/t/n-eff-bda3-vs-stan/2608/19 for some further explanation.

And for the autocorrelation plot:

Positive autocorrelation is bad (it means the chain tends to stay in the same area between iterations) and you want it to drop quickly to zero with increasing lag. Negative autocorrelation is possible and it is useful as it indicates fast convergence towards true mean.

**Comment by avehtari** [comment]
Excellent!

>  Other functions computed from draws (quantiles, posterior intervals, tail probabilities) may not necessarily approach the true posterior faster.

This is important point.

**Comment by martinmodrak** [comment]
Ok, it's there. Turns out getting the traceplot zoom example to work on all systems is a bit of a headache :-(

**Comment by martinmodrak** [comment]
OK, it turns out I was wrong - `n_eff` is explained quite well in the manual, I just never paid attention :-D. Sorry for the too quick conclusion above.

**Comment by avehtari** [comment]
I had a quick look of the updated version (I guess this is the latest https://popelka.ms.mff.cuni.cz/~cerny/tmp/visual-mcmc-diagnostics-wip.html ?)

> compare_cp_ncp(mcmc_neff(neff_cp), mcmc_neff(neff_ncp), ncol = 1)

Seems to be truncating N_eff/N to 1?

> means that the mean value of the parameter computed from Stan draws approaches the true mean faster then independent samples from the true posterior 

-> means that the mean estimate of the parameter computed from Stan draws approaches the true mean faster than the mean estimate computed from independent samples from the true posterior

**Comment by martinmodrak** [comment]
Reworded. The truncation at N_eff/N = 1 happens in currently released RStan and is removed in develop. I switched between develop and the CRAN version recently, so the vignette I have is with truncation. I also replaced the WIP version with the one created with the develop version of Rstan where the truncation does not happen.

**Comment by avehtari** [comment]
Ok.

**Comment by avehtari** [comment]
@martinmodrak great work! I approved changes, so now github let's to merge

**Comment by jgabry** [comment]
These changes look good to me. Thanks! I think this is probably ready to merge. @martinmodrak anything else you wanted to add before I merge this?

**Comment by martinmodrak** [comment]
Nothing. Ready to merge.

**Comment by tjmahr** [comment]
I just caught up on the neff discussion. That is super interesting! I wrote the neff validation function with that assumption that neff / N could never exceed 1 because that's how it seems (intuitively).

Btw I'd like to do a run through and pull request to copyedit the vignette eventually.

**Comment by jgabry** [comment]
@tjmahr sounds good. I’m sure other vignettes could use some copy editing too;)

**Pull request merged**
