### PR TITLE
Feature tidyselect

### LINKED ISSUE #161: Exclude parameters (eg: "lp__")
Perhaps I've missed something, but I can't find a simple way to exclude a parameter. For something like `mcmc_parcoord` I often want to remove "lp__" and display all other parameters.

I thought I could use negative lookaheads, but R needs an extra flag for Perl compatible expressions. Can this be passed through to `base::grep`?

```R
 grepl("^(?!lp).*$", c("par_1", "lp__"), perl = F)
> Error in grepl("^(?!lp).*$", c("par_1", "lp__"), perl = F) : 
> invalid regular expression '^(?!lp).*$', reason 'Invalid regexp'

grepl("^(?!lp).*$", c("par_1", "lp__"), perl = T)
> [1]  TRUE FALSE
```

### LINKED ISSUE #183: 'tidy' parameter selection
As discussed in #161, we should enable parameter selection using `vars(...)`. The version of this now implemented in the [`feature-tidyselect`](https://github.com/stan-dev/bayesplot/tree/feature-tidyselect) branch works by allowing the `pars` argument to be a list of quosures, as returned by `dplyr::vars`, with a call to `tidyselect::vars_select()` internally. For example, 

```r
x <- example_mcmc_draws()
mcmc_hist(x, pars = vars(-contains("beta"))
mcmc_hist(x, pars = vars(alpha, sigma)) 
```

The behavior of `pars` when it is a character vector is unchanged.

### PR DESCRIPTION
**Pull request by jgabry**
Closes #161 
Closes #183 

This PR allows the `pars` argument to MCMC plots be a list of quosures, as returned by `dplyr::vars()`. Internally **bayesplot** will call `tidyselect::vars_select()` if `pars` is a list of quosures. If `pars` is just a character vector then the behavior is unchanged from previous versions of **bayesplot**, which preserves backwards compatibility. 

### Example usage

```r
x <- example_mcmc_draws()
mcmc_hist(x, pars = vars(-contains("beta"))
mcmc_hist(x, pars = vars(alpha, sigma))
```

### Important changes for review

The important changes for review are in `helpers-mcmc.R` 

https://github.com/stan-dev/bayesplot/blob/eef7bc88877bb7737a7643c49337c88a48b92677/R/helpers-mcmc.R#L31-L38

and the new file `tidy-params.R`, which is mostly for examples of tidy parameter selection but also contains this new internal function: 

https://github.com/stan-dev/bayesplot/blob/eef7bc88877bb7737a7643c49337c88a48b92677/R/tidy-params.R#L73-L81

### CODE REVIEW

**Comment by jgabry** [comment]
Given that this PR makes it possible to use the [tidyselect helpers](https://www.rdocumentation.org/packages/tidyselect/versions/0.2.5/topics/select_helpers) (e.g., `starts_with()`, `num_range()`, etc.) to select parameters, does it make sense to provide some additional helpers that are convenient? 

For example, if parameters are named `"beta1",` `"beta2"`, ..., `"beta10"` and we want to select just 2 through 7 then the `num_range()` tidyselect helper works great: 
```r
mcmc_hist(..., pars = vars(num_range("beta", 2:7)))
``` 
but `num_range()` doesn't work if the parameters have brackets in their names like `"beta[1]",` `"beta[2]"`, ..., `"beta[10]"`, which is far more common. But we could conceivably export a helper function like this:
```r
param_range <- function(prefix, range) {
  nms <- paste0(prefix, "[", range, "]")
  param_matches <- match(nms, table = tidyselect::peek_vars())
  param_matches[!is.na(param_matches)]
}
```
which would enable
```r
mcmc_hist(..., pars = vars(param_range("beta", 2:7)))
```

**Comment by tjmahr** [comment]
> `num_range()` doesn't work if the parameters have brackets in their names like `"beta[1]",` `"beta[2]"`, ..., `"beta[10]"`, which is far more common. But we could conceivably export a helper function like this:

This is great.

**Comment by jgabry** [comment]
Ok cool I’ll add that to the PR.

**Comment by tjmahr** [comment]
I was worried about mixed models where you get a lot going on the brackets, so I tried to make a general one. This would require glue, but glue is dependency-less and it is required by most of the tidyverse packages that we already depend on.

``` r
library(tidyverse)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
d <- structure(list(b_Intercept = c(0.25, 0.13, 0.77, 0.67, 0.44, 
0.33), sd_condition__Intercept = c(1.01, 1.01, 0.78, 0.77, 0.89, 
0.76), sigma = c(0.63, 0.54, 0.62, 0.59, 0.47, 0.44), `r_condition[A,Intercept]` = c(-0.2, 
0.16, -0.82, -0.28, -0.53, -0.25), `r_condition[B,Intercept]` = c(0.98, 
0.53, 0.44, 0.15, 0.74, 0.41), `r_condition[C,Intercept]` = c(1.33, 
1.79, 0.83, 1.5, 1.15, 1.54), `r_condition[A,Slope]` = c(0.86, 
0.78, 0.19, -0.14, 0.87, 0.49), `r_condition[B,Slope]` = c(-1.18, 
-0.96, -1.66, -1.62, -1.53, -1.1), lp__ = c(-51.66, -51.15, -53.32, 
-56.79, -56.48, -54.96)), class = c("tbl_df", "tbl", "data.frame"
), row.names = c(NA, -6L))
  
param_glue <- function(pattern, ...) {
  dots <- as.list(expand.grid(...))
  nms <- as.character(glue::glue_data(dots, pattern))

  param_matches <- match(nms, tidyselect::peek_vars())
  param_matches[!is.na(param_matches)]
}

d
#> # A tibble: 6 x 9
#>   b_Intercept sd_condition__I~ sigma `r_condition[A,~ `r_condition[B,~
#>         <dbl>            <dbl> <dbl>            <dbl>            <dbl>
#> 1        0.25             1.01  0.63            -0.2              0.98
#> 2        0.13             1.01  0.54             0.16             0.53
#> 3        0.77             0.78  0.62            -0.82             0.44
#> 4        0.67             0.77  0.59            -0.28             0.15
#> 5        0.44             0.89  0.47            -0.53             0.74
#> 6        0.33             0.76  0.44            -0.25             0.41
#> # ... with 4 more variables: `r_condition[C,Intercept]` <dbl>,
#> #   `r_condition[A,Slope]` <dbl>, `r_condition[B,Slope]` <dbl>, lp__ <dbl>

d %>% 
  select(
    param_glue(
      "r_condition[{level},Intercept]", 
      level = c("A", "B"))
  )
#> # A tibble: 6 x 2
#>   `r_condition[A,Intercept]` `r_condition[B,Intercept]`
#>                        <dbl>                      <dbl>
#> 1                      -0.2                        0.98
#> 2                       0.16                       0.53
#> 3                      -0.82                       0.44
#> 4                      -0.28                       0.15
#> 5                      -0.53                       0.74
#> 6                      -0.25                       0.41

d %>% 
  select(
    param_glue(
      "r_condition[{level},{type}]", 
      level = c("A", "B"), 
      type = c("Intercept", "Slope"))
    )
#> # A tibble: 6 x 4
#>   `r_condition[A,In~ `r_condition[B,In~ `r_condition[A,S~ `r_condition[B,S~
#>                <dbl>              <dbl>             <dbl>             <dbl>
#> 1              -0.2                0.98              0.86             -1.18
#> 2               0.16               0.53              0.78             -0.96
#> 3              -0.82               0.44              0.19             -1.66
#> 4              -0.28               0.15             -0.14             -1.62
#> 5              -0.53               0.74              0.87             -1.53
#> 6              -0.25               0.41              0.49             -1.1
```

<sup>Created on 2019-05-20 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by jgabry** [comment]
Good idea!

**Comment by jgabry** [comment]
I’ll incorporate that.

**Comment by jgabry** [comment]
I think this is ready to go.

**Comment by tjmahr** [comment]
I expanded the documentation to `tidy-params` to include all the `select()` gotchas I could think of. Everything else seems fine.

**Comment by jgabry** [comment]
Awesome, thanks!

**Pull request merged**
