### PR TITLE
Add option 'bins' to histogram functions

### PR DESCRIPTION
**Pull request by heavywatal**

### CODE REVIEW

**Comment by heavywatal** [comment]
Resolved all conflicts after `git rebase master`. This PR is almost one year old.

**Comment by jgabry** [comment]
Sorry this never got merged! I think I forgot about it because https://github.com/stan-dev/bayesplot/pull/300 came in and accomplished the same thing. However I realize now that #300 was missing the NUTS diagnostic plots. I'm going to close this one because #300 was merged, but do you want to submit a separate PR just adding `bins` to the NUTS plots? 

It's been so long that I understand if you don't want to do it anymore. In that case I am happy to make the changes myself but credit you for the changes in the NEWS file and add your handle to the commits I make. Whatever you prefer. Apologies again for not dealing with this sooner (I have been focused on other packages for a while and we're finally preparing another bayesplot release).

**Comment by jgabry** [comment]
(closing but see comment above)

**Comment by heavywatal** [comment]
@jgabry No problem. Thank you for your efforts. I will submit another PR for missing ones as you suggested.

**Comment by jgabry** [comment]
Great, thank you!

**Pull request closed without merging**
