### PR TITLE
Rank histogram

### PR DESCRIPTION
**Pull request by tjmahr**
This is a work-in-progress pull request to address #178.

So far I've added mcmc_trace_data() which prepares a dataframe of the values in each chain. While I was at it, I refactored mcmc_trace() to take advantage of this function. 

The results mcmc_trace_data() includes a column `value_rank`. With this addition, we can very quickly make histogram of ranks. 

Here is a prototype of the main steps.

``` r
library(bayesplot)
#> This is bayesplot version 1.6.0.9000
#> - Online documentation and vignettes at mc-stan.org/bayesplot
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
library(tidyverse)
#> Warning: package 'tibble' was built under R version 3.5.3
#> Warning: package 'purrr' was built under R version 3.5.3

x <- example_mcmc_draws(params = 4)

d <- bayesplot:::mcmc_trace_data(x)
n_iter <- unique(d$n_iterations)
n_chains <- unique(d$n_chains)

d_boundaries <- d %>% 
  dplyr::distinct(chain, parameter) 

d_boundaries <- dplyr::bind_rows(
    mutate(d_boundaries, value_rank = min(d$value_rank)),
    mutate(d_boundaries, value_rank = max(d$value_rank))
  )

# Print parameter and chain on one line
labeller <- function(x) label_value(x, multi_line = FALSE)

ggplot(d) + 
  aes(x = value_rank) + 
  geom_histogram(boundary = 0, bins = 20, color = "white") + 
  facet_wrap(
    c("parameter", "chain"), dir = "v",
    nrow = n_chains, 
    # Need free_x to have the x axis under each facet
    scales = "free_x", 
    labeller = labeller) +
  # Draw blank data to fix the range in each facet
  geom_blank(data = d_boundaries)
```

<sup>Created on 2019-03-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### CODE REVIEW

**Comment by jgabry** [comment]
Thanks for working on this TJ!

**Comment by tjmahr** [comment]
I've added `mcmc_rank_overlay()` which is inspired by Richard McElreath's [version of the histograms](https://twitter.com/rlmcelreath/status/1113797716835016705). 

I also added `"viridisE"` which is the ["cividis" variant](https://github.com/marcosci/cividis) of viridis to the viridis color scale.

``` r
library(bayesplot)
#> This is bayesplot version 1.6.0.9000
#> - Online documentation and vignettes at mc-stan.org/bayesplot
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
x <- example_mcmc_draws(params = 4)
bayesplot::color_scheme_set("viridisE")
mcmc_rank_overlay(x, "alpha")
```



<sup>Created on 2019-04-05 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by jgabry** [comment]
Nice! Let me know if/when this is ready for review.

**Comment by tjmahr** [comment]
I should add a horizontal line at uniform height... https://arviz-devs.github.io/arviz/generated/arviz.plot_rank.html

**Comment by avehtari** [comment]
Do I read the pull request correctly that it doesn't yet have a function which would plot the rank histograms in different subplots? (I don't like the overlaid histograms as they get easily messy).

**Comment by tjmahr** [comment]
> Do I read the pull request correctly that it doesn't yet have a function which would plot the rank histograms in different subplots? (I don't like the overlaid histograms as they get easily messy). -- @ave

I've added `mcmc_rank_hist()`.

``` r
library(bayesplot)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
#> This is bayesplot version 1.6.0.9000
#> - Online documentation and vignettes at mc-stan.org/bayesplot
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
x <- example_mcmc_draws()
color_scheme_set("viridisE")
mcmc_rank_hist(x, c("beta[1]"))
```



``` r
mcmc_rank_hist(x, c("alpha", "beta[1]"))
```



<sup>Created on 2019-05-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by avehtari** [comment]
> I've added mcmc_rank_hist().

Great! I would remove y axis

**Comment by tjmahr** [comment]
> 
> 
> > I've added mcmc_rank_hist().
> 
> Great! I would remove y axis

I have removed the y-axis and created an option to show a reference line.

``` r
library(bayesplot)
#> This is bayesplot version 1.6.0.9000
#> - Online documentation and vignettes at mc-stan.org/bayesplot
#> - bayesplot theme set to bayesplot::theme_default()
#>    * Does _not_ affect other ggplot2 plots
#>    * See ?bayesplot_theme_set for details on theme setting
x <- example_mcmc_draws()
color_scheme_set("viridisE")
mcmc_rank_hist(x, c("beta[1]"))
```



``` r
mcmc_rank_hist(x, c("beta[1]"), ref_line = TRUE)
```



``` r

mcmc_rank_hist(x, c("alpha", "beta[1]"), n_bins = 10)
```



``` r
mcmc_rank_hist(x, c("alpha", "beta[1]"), ref_line = TRUE)
```



<sup>Created on 2019-05-21 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by tjmahr** [comment]
Ready for review.

**Comment by jgabry** [comment]
@tjmahr this looks great. Quick question: the `size`, `np`, and `np_style` arguments do not appear to be used inside `mcmc_trace_data()`. Can I remove these arguments?

**Comment by tjmahr** [comment]
> 
> 
> @tjmahr this looks great. Quick question: the `size`, `np`, and `np_style` arguments do not appear to be used inside `mcmc_trace_data()`. Can I remove these arguments?

Yes. Good catch. Then be sure to update the call to `mcmc_trace_data()` in `.mcmc_trace()`.

**Comment by avehtari** [comment]
> I have removed the y-axis and created an option to show a reference line.

Looks good!

**Comment by jgabry** [comment]
Actually same goes for the `window` argument, but for that one there’s a todo note about maybe having `mcmc_trace_data()` return only the specified window:

https://github.com/stan-dev/bayesplot/blob/0eac0c3cfe9f6bacc87efad8bc951576422f76be/R/mcmc-traces.R#L464

I’m ok with either option (keeping it as is or having `mcmc_trace_data()` handle the window), so your call. Did you want to decide on this before I merge this or hold off and maybe do it in the future?

**Comment by tjmahr** [comment]
I think we can drop `window` and the note there too. I wasn't sure at the time when I wrote the note.
 
But we never do `filter()` the data to the window (we just set the coordinate limits to the window) so we don't need to make it part of the data preparation.

**Comment by jgabry** [comment]
Ok sounds good. I'll take care of it.

**Pull request merged**
